//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOwnerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeRegNoItemsS1
    {
        public int Id { get; set; }
        public Nullable<int> RegId { get; set; }
        public Nullable<int> ItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual RegistrationNoS1 RegistrationNoS1 { get; set; }
    }
}
