//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterOwnerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.BridgeRegNoItemS2 = new HashSet<BridgeRegNoItemS2>();
            this.BridgeRegNoItemsS1 = new HashSet<BridgeRegNoItemsS1>();
            this.BridgeRegNoItemsS3 = new HashSet<BridgeRegNoItemsS3>();
            this.BridgeRegNoItemsS4 = new HashSet<BridgeRegNoItemsS4>();
            this.BridgeRegNoItemsS5 = new HashSet<BridgeRegNoItemsS5>();
            this.BridgeRegNoItemsS6 = new HashSet<BridgeRegNoItemsS6>();
            this.BridgeRegNoItemsS7 = new HashSet<BridgeRegNoItemsS7>();
            this.BridgeRegNosItemS8 = new HashSet<BridgeRegNosItemS8>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Producer { get; set; }
        public string Model { get; set; }
        public string ItemId { get; set; }
        public string ItemSerial { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<System.DateTime> DateofPurchase { get; set; }
        public string ReceiptImage { get; set; }
        public Nullable<bool> BoolDateOfPurchase { get; set; }
        public Nullable<bool> BoolPlace { get; set; }
        public Nullable<bool> BoolItem { get; set; }
        public Nullable<bool> BoolAdress { get; set; }
        public Nullable<bool> BoolFirstName { get; set; }
        public Nullable<bool> BoolLastName { get; set; }
        public Nullable<bool> BoolPhoneNo { get; set; }
        public Nullable<bool> BoolEmail { get; set; }
        public Nullable<bool> BoolReceipt { get; set; }
    
        public virtual ICollection<BridgeRegNoItemS2> BridgeRegNoItemS2 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS1> BridgeRegNoItemsS1 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS3> BridgeRegNoItemsS3 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS4> BridgeRegNoItemsS4 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS5> BridgeRegNoItemsS5 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS6> BridgeRegNoItemsS6 { get; set; }
        public virtual ICollection<BridgeRegNoItemsS7> BridgeRegNoItemsS7 { get; set; }
        public virtual ICollection<BridgeRegNosItemS8> BridgeRegNosItemS8 { get; set; }
    }
}
