//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementSystem26_10_17.RegisterOwnerDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentRegistrationNo
    {
        public int Id { get; set; }
        public string OneDigit { get; set; }
        public string TwoDigit { get; set; }
        public string ThreeDigit { get; set; }
        public string FourDigit { get; set; }
        public string FiveDigit { get; set; }
        public string SixDigit { get; set; }
        public string SevenDigit { get; set; }
        public string EightDigit { get; set; }
    }
}
