//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementSystem26_10_17.RegisterOwnerDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOwnerHistory
    {
        public int Id { get; set; }
        public int ItemIdMain { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<bool> BoolDateOfPurchase { get; set; }
        public Nullable<bool> BoolItem { get; set; }
        public Nullable<bool> BoolPlace { get; set; }
        public Nullable<bool> BoolAdress { get; set; }
        public Nullable<bool> BoolFirstName { get; set; }
        public Nullable<bool> BoolLastName { get; set; }
        public Nullable<bool> BoolPhoneNo { get; set; }
        public Nullable<bool> BoolEmail { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public string Place { get; set; }
        public string MobileNo { get; set; }
        public string RegNo { get; set; }
    }
}
