//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagementSystem26_10_17.RegisterOwnerDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegisterOwnersContext : DbContext
    {
        public RegisterOwnersContext()
            : base("name=RegisterOwnersContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BridgeRegNoItemS2> BridgeRegNoItemS2 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS1> BridgeRegNoItemsS1 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS3> BridgeRegNoItemsS3 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS4> BridgeRegNoItemsS4 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS5> BridgeRegNoItemsS5 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS6> BridgeRegNoItemsS6 { get; set; }
        public virtual DbSet<BridgeRegNoItemsS7> BridgeRegNoItemsS7 { get; set; }
        public virtual DbSet<BridgeRegNosItemS8> BridgeRegNosItemS8 { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<RegistrationNoS1> RegistrationNoS1 { get; set; }
        public virtual DbSet<RegistrationNoS2> RegistrationNoS2 { get; set; }
        public virtual DbSet<RegistrationNoS3> RegistrationNoS3 { get; set; }
        public virtual DbSet<RegistrationNoS4> RegistrationNoS4 { get; set; }
        public virtual DbSet<RegistrationNoS5> RegistrationNoS5 { get; set; }
        public virtual DbSet<RegistrationNoS6> RegistrationNoS6 { get; set; }
        public virtual DbSet<RegistrationNoS7> RegistrationNoS7 { get; set; }
        public virtual DbSet<RegistrationNoS8> RegistrationNoS8 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CurrentRegistrationNo> CurrentRegistrationNoes { get; set; }
    }
}
